services:
  nginx:
    image: nginx:latest
    platform: linux/arm64/v8
    ports:
      - "3900:80"
    volumes:
      - .dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - backend

  client:
    image: node:20
    platform: linux/arm64/v8
    ports:
      - 3901:3000
    volumes:
      - .:/app
    working_dir: /app/client
    environment:
      BACKEND_URL: backend:3000
    entrypoint: ["bash", "-c", "yarn && yarn dev"]

  backend:
    image: node:20
    platform: linux/arm64/v8
    ports:
      - 3902:3000
    environment:
      DATABASE_URL: "mysql://root@db/brainwaves"
    volumes:
      - .:/app
    working_dir: /app/server
    entrypoint:
      [
        "../.dev/wait-for-it.sh",
        "db:3306",
        "--",
        "bash",
        "-c",
        "yarn && yarn dev",
      ]

  db:
    ports:
      - 3903:3306
    image: "mysql:8.0"
    platform: linux/arm64/v8
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: brainwaves

volumes:
  db: {}
