name: "Worker Status"

on:
  # every hour
  schedule:
    - cron: "0 * * * *"
  # manual trigger
  workflow_dispatch:

jobs:
  check_worker_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
